config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'

  root 'pages#start'
  devise_for :users, controllers: {sessions: 'user_sessions'}
  [:about, :start, :formats, :test].each do |p|
    get "/#{p}", to: "pages##{p}"
  end

  namespace :admin do
    resources :organizations
    resources :users do
      member do
        patch 'update_roles', as: :update_roles
      end
    end
    get 'dashboard', to: 'dashboard#index'
    constraints lambda { |request| request.env['warden'].authenticate? && request.env['warden'].user.superadmin? } do
      mount Resque::Server.new, at: "resque"
    end
  end

  get "organization_selector", to: "dashboard#organization_selector"
  get ':organization_slug', to: 'organizations#show', as: 'organization'
  patch ':organization_slug', to: 'organizations#update'

  scope ':organization_slug' do
    get "dashboard", to: "dashboard#index"

    resources :accounting_periods do
      member do
        post 'import_sie', as: :import_sie_files
      end
    end

    post 'accounting_plan_import', to: 'accounting_plans#import', as: 'accounting_plan_import'
    resources :accounting_plans do
      resources :accounting_groups
      resources :accounting_classes
      resources :accounts
    end

    resources :closing_balances do
      resources :closing_balance_items
    end

    resources :contact_relations
    resources :contacts
    resources :conversions do
      delete 'clear'
    end
    resources :employees

    resources :import_bank_files do
      resources :import_bank_file_rows
    end

    get  'import_sie_files/order_import_sie'
    post 'import_sie_files/import_sie'

    resources :ink_codes
    resources :ledgers do
      resources :ledger_accounts
    end
    resources :ledger_transactions

    resources :opening_balances do
      post 'create_from_ub'
      resources :opening_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end

    get 'reports/order_verificates_report'
    get 'reports/order_ledger_report'
    get 'reports/order_result_report'
    get 'reports/order_balance_report'
    post 'reports/verificates'
    post 'reports/ledger'
    post 'reports/result_report'
    post 'reports/balance_report'

    resources :result_units
    resources :tax_codes

    resources :tax_returns do
      resources :tax_return_reports
      member do
        post 'create_tax_return_report', as: :create_tax_return_report
      end
    end

    resources :templates do
      resources :template_items
    end

    resources :users do
      member do
        patch :update_roles, as: :update_roles
      end
    end

    resources :vat_periods do
      resources :vat_reports
      member do
        post 'create_verificate', as: :create_verificate
        post 'create_vat_report', as: :create_vat_report
      end
    end

    resources :verificates do
      resources :verificate_items
      member do
        post 'state_change', as: :state_change
        post 'add_verificate_items', as: :add_verificate_items
      end
    end

    resources :wage_periods do
      resources :wages
      resources :wage_reports
      member do
        post 'create_wage', as: :create_wage
        post 'create_wage_verificate', as: :create_wage_verificate
        post 'create_wage_report', as: :create_wage_report
        post 'create_report_verificate', as: :create_report_verificate
      end
    end

  end

end

app/models/wage.rb
class Wage < ActiveRecord::Base
  # t.datetime :wage_from
  # t.datetime :wage_to
  # t.datetime :payment_date
  # t.decimal  :salery
  # t.decimal  :addition
  # t.decimal  :discount
  # t.decimal  :tax
  # t.decimal  :amount
  # t.integer  :organization_id
  # t.integer  :accounting_period_id
  # t.integer  :wage_period_id
  # t.integer  :employee_id

  attr_accessible :wage_from, :wage_to, :payment_date, :salary, :addition, :discount, :tax, :payroll_tax, :amount

  belongs_to :organization
  belongs_to :accounting_period
  belongs_to :wage_period
  belongs_to :employee
  has_one :verificate

  validates :accounting_period, presence: true
  validates :employee, presence: true
  validates :wage_from, presence: true
  validates :wage_to, presence: true
  validates :payment_date, presence: true

  def can_delete?
    return true if wage_period.can_calculate_wage?
    false
  end
end

app/controllers/wages_controller.rb
class WagesController < ApplicationController
  respond_to :html, :json
  load_and_authorize_resource :wage_period, through: :current_organization
  load_and_authorize_resource :wage, through: :wage_period

  before_filter :new_breadcrumbs, only: [:new, :create]
  before_filter :show_breadcrumbs, only: [:edit, :show, :update]

  # GET /wages
  # GET /wages.json
  def index
    @breadcrumbs = [['Wage periods', wage_periods_path],
                    [@wage_period.name, wage_period_path(@wage_period.id)],
                    ['Wages']]
    @wage_periods = current_organization.wage_periods.order('id')
    if !params[:wage_period_id] && @wage_periods.count > 0
      params[:wage_period_id] = @wage_periods.first.id
    end
    @wages = current_organization.wages.where('wage_period_id=?', params[:wage_period_id])
    @wages = @wages.page(params[:page]).decorate
  end

  # GET /wages/new
  def new
    @wage_periods = current_organization.wage_periods
    @wage.wage_from = @wage_period.wage_from
    @wage.wage_to = @wage_period.wage_to
    @wage.payment_date = @wage_period.payment_date
  end

  # GET /wages/1
  def show

  end

  # GET /wage/1/edit
  def edit
    @wage_periods = current_organization.wage_periods
  end

  # POST /wages
  # POST /wages.json
  def create
    @wage = Wage.new(wage_params)
    @wage.organization = current_organization
    respond_to do |format|
      if @wage.save
        format.html { redirect_to wage_period_wages_path, notice: "#{t(:wage)} #{t(:was_successfully_created)}" }
      else
        @wage_periods = current_organization.wage_periods
        flash.now[:danger] = "#{t(:failed_to_create)} #{t(:wage)}"
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @wage.update(wage_params)
        format.html { redirect_to wage_period_wages_path, notice: "#{t(:wage)} #{t(:was_successfully_updated)}" }
      else
        @wage_periods = current_organization.wage_periods
        flash.now[:danger] = "#{t(:failed_to_update)} #{t(:wage)}"
        format.html { render action: 'show' }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @wage.destroy
    respond_to do |format|
      format.html { redirect_to wage_period_wages_path, notice: "#{t(:wage)} #{t(:was_successfully_deleted)}" }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def wage_params
    params.require(:wage).permit(Wage.accessible_attributes.to_a)
  end

  def new_breadcrumbs
    @breadcrumbs = [['Wage periods', wage_periods_path], [@wage.wage_period.name, wage_period_path(@wage.wage_period_id)],
                    ['Wages', wage_period_wages_path(@wage.wage_period_id)],
                    ['New wage']]
  end

  def show_breadcrumbs
    @breadcrumbs = [['Wage periods', wage_periods_path], [@wage.wage_period.name, wage_period_path(@wage.wage_period_id)],
                    ['Wages', wage_period_wages_path(@wage.wage_period_id)],
                    [@wage.employee.name]]
  end
end

app/views/wages/_form.html.haml
%div{ng_controller: 'wage_form_ctrl', ng_init: 'init()' }
  = simple_form_for([@wage_period, @wage], wrapper: :horizontal_form, html: {class: 'form-horizontal'}) do |f|
    = f.error_notification
    = f.association :wage_period, collection: @wage_periods, include_blank: false, disabled: true
    = f.association :employee, disabled: !@wage.new_record?
    = render partial: 'shared/date_field', locals: {form: f, field: :wage_from, in_id: 'in_from', in_value: @wage.wage_from, out_id: 'wage[wage_from]', field_id: 'from_short_date',  model: 'from_date', dp_open: 'from_open', dp_options: 'from_options', dp_click: 'open_from_date($event)'}
    .error_width
      = f.error :wage_from
    = render partial: 'shared/date_field', locals: {form: f, field: :wage_to, in_id: 'in_to', in_value: @wage.wage_to, out_id: 'wage[wage_to]', field_id: 'to_short_date',  model: 'to_date', dp_open: 'to_open', dp_options: 'to_options', dp_click: 'open_to_date($event)'}
    .error_width
      = f.error :wage_to
    = render partial: 'shared/date_field', locals: {form: f, field: :payment_date, in_id: 'in_payment', in_value: @wage.payment_date, out_id: 'wage[payment_date]', field_id: 'payment_short_date',  model: 'payment_date', dp_open: 'payment_open', dp_options: 'payment_options', dp_click: 'open_payment_date($event)'}
    .error_width
      = f.error :payment_date
    = f.input :salary
    = f.input :addition
    = f.input :discount
    = f.input :tax
    = f.input :amount
    = f.input :payroll_tax

    - if @wage.can_delete?
      .form-button-group
        .actions
          = f.submit class: 'btn btn-primary'

app/views/wages/index.html.haml
- if @wage_period.can_report_wage?
  = link_to "#{t(:create)} #{t(:wage)}", new_wage_period_wage_path(@wage_period), class: 'btn btn-success'
  = link_to "#{t(:create)} #{t(:verificate)}", create_wage_verificate_wage_period_path(params[:wage_period_id]), method: 'post', class: 'btn btn-success'

.table-responsive{:ng_controller=>'ModalCtrl'}
  %table{:class => 'table table-striped'}
    %thead
      %tr
        %th= t(:name)
        %th= t(:from)
        %th= t(:to)
        %th= t(:payment_date)
        %th.numeric= t(:tax)
        %th.numeric= t(:amount)
        %th
        %th
    %tbody{}
      - @wages.each do |wage|
        %tr
          %td= wage.employee.name
          %td= wage.wage_from
          %td= wage.wage_to
          %td= wage.payment_date
          %td.numeric= wage.tax
          %td.numeric= wage.amount
          %td.numeric= link_to settings_icon, edit_wage_period_wage_path(@wage_period, wage)
          %td.numeric= delete_modal_for wage, wage_period_wage_path(@wage_period, wage)

  = paginate @wages, :theme => 'twitter-bootstrap-3'
  = render partial: 'shared/modal_delete', locals: {idx: 'deleteContent'}