config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'

  root 'pages#start'
  devise_for :users, controllers: {sessions: 'user_sessions'}
  [:about, :start, :formats, :test].each do |p|
    get "/#{p}", to: "pages##{p}"
  end

  namespace :admin do
    resources :organizations
    resources :users do
      member do
        patch 'update_roles', as: :update_roles
      end
    end
    get 'dashboard', to: 'dashboard#index'
    constraints lambda { |request| request.env['warden'].authenticate? && request.env['warden'].user.superadmin? } do
      mount Resque::Server.new, at: "resque"
    end
  end

  get "organization_selector", to: "dashboard#organization_selector"
  get ':organization_slug', to: 'organizations#show', as: 'organization'
  patch ':organization_slug', to: 'organizations#update'

  scope ':organization_slug' do
    get "dashboard", to: "dashboard#index"

    resources :accounting_periods do
      member do
        post 'import_sie', as: :import_sie_files
      end
    end

    post 'accounting_plan_import', to: 'accounting_plans#import', as: 'accounting_plan_import'
    resources :accounting_plans do
      resources :accounting_groups
      resources :accounting_classes
      resources :accounts
    end

    resources :closing_balances do
      resources :closing_balance_items
    end

    resources :contact_relations
    resources :contacts
    resources :conversions do
      delete 'clear'
    end
    resources :employees

    resources :import_bank_files do
      resources :import_bank_file_rows
    end

    get  'import_sie_files/order_import_sie'
    post 'import_sie_files/import_sie'

    resources :ink_codes
    resources :ledgers do
      resources :ledger_accounts
    end
    resources :ledger_transactions

    resources :opening_balances do
      post 'create_from_ub'
      resources :opening_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end

    get 'reports/order_verificates_report'
    get 'reports/order_ledger_report'
    get 'reports/order_result_report'
    get 'reports/order_balance_report'
    post 'reports/verificates'
    post 'reports/ledger'
    post 'reports/result_report'
    post 'reports/balance_report'

    resources :result_units
    resources :tax_codes

    resources :tax_returns do
      resources :tax_return_reports
      member do
        post 'create_tax_return_report', as: :create_tax_return_report
      end
    end

    resources :templates do
      resources :template_items
    end

    resources :users do
      member do
        patch :update_roles, as: :update_roles
      end
    end

    resources :vat_periods do
      resources :vat_reports
      member do
        post 'create_verificate', as: :create_verificate
        post 'create_vat_report', as: :create_vat_report
      end
    end

    resources :verificates do
      resources :verificate_items
      member do
        post 'state_change', as: :state_change
        post 'add_verificate_items', as: :add_verificate_items
      end
    end

    resources :wage_periods do
      resources :wages
      resources :wage_reports
      member do
        post 'create_wage', as: :create_wage
        post 'create_wage_verificate', as: :create_wage_verificate
        post 'create_wage_report', as: :create_wage_report
        post 'create_report_verificate', as: :create_report_verificate
      end
    end

  end

end

app/views/shared/_breadcrumb.html.haml
%ul.breadcrumb
  -@breadcrumbs.each do |item|
    - if item.size > 1
      %li= link_to item[0], item[1]
    -else
      %li.active=item[0]

app/views/shared/_date_field.html.haml
- out_value = '{{'+model+'}}'
.form-group
  = form.label field, class: 'string optional labels_width control-label'
  .fields_width
    = hidden_field_tag in_id, in_value
    = hidden_field_tag out_id, out_value
    .input-group.date
      = text_field_tag field_id, '', class: 'form-control', ng_model: model, datepicker_popup: 'yyyy-MM-dd', is_open: dp_open, min_date: 'min_date', max_date: 'max_date', datepicker_options: dp_options, show_button_bar: 'false', readonly: true
      %span{:class => "input-group-btn"}
        %button{:class => "btn btn-default", :ng_click=> dp_click }
          %span{ :class => "glyphicon glyphicon-calendar"}

app/views/shared/_footer.html.haml
%footer
  .container-fluid
    .row
      .col-md-48
        %ul
          %li
            = t(:fork_me)
            = link_to 'github.com/dulvie/kinna', 'https://github.com/dulvie/kinna'
          %li
            = t(:feedback_at)
            = link_to 'github', 'https://github.com/dulvie/kinna/issues'

app/views/shared/_modal_delete.html.haml
%script{ :type=>"text/ng_template", :id=>idx}
  .modal-header
    %h3{ :class=>"modal-title"}
      = t(:confirm_delete)
  .modal-body
    = link_to t(:confirm), '{{obj}}', method: :delete,  class: 'btn btn-primary'
    = button_tag t(:back), class: 'btn btn-default reseter', type: 'reset', :ng_click=>"cancel()"

app/views/shared/_modal_state_change.html.haml
%script{ :type=>"text/ng_template", :id=>idx}
  .modal-header
    %h3{ :class=>"modal-title"}
      = t(:set_date)

  .modal-body
    = simple_form_for(model, url: form_path, method: :post) do |f|
      = hidden_field_tag 'event', event
      = hidden_field_tag 'return_path', return_path
      .form-group
        .input-group
          = hidden_field_tag "state_change_at", "{{date}}"
          = text_field_tag "short_date", '', class: 'form-control', ng_model: 'date', datepicker_popup: 'yyyy-MM-dd', is_open: 'isOpen', min_date: 'min_date', max_date: 'max_date', datepicker_options: 'dpOptions', show_button_bar: 'false', readonly: true
          %span{:class => "input-group-btn"}
            %button{:class => "btn btn-default", :ng_click=>'openDate($event)' }
              %span{ :class => "glyphicon glyphicon-calendar"}
      = submit_tag t(:confirm), class: 'btn btn-primary'
      = button_tag t(:back), class: 'btn btn-danger reseter', type: 'reset', :ng_click=>"cancel()"

app/views/shared/_navigation.html.haml
.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle{'data-toggle' => 'collapse', 'data-target' => '#navbar-collapse'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to 'Kinna', root_path, class: 'navbar-brand'

    #navbar-collapse.collapse.navbar-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav
          - if current_organization
            = nav_link "Dashboard", dashboard_path
          %li.dropdown
            %a.dropdown-toggle{'href' => '#'}
              = t(:general)
              %b.caret
            %ul.dropdown-menu
              = nav_link t(:organization_selector), organization_selector_path
              - if current_organization
                = nav_link t(:organization), organization_path
                = nav_link t(:users), users_path
                = nav_link t(:accounting_plans), accounting_plans_path
                = nav_link t(:tax_codes), tax_codes_path
                = nav_link t(:ink_codes), ink_codes_path
                = nav_link t(:templates), templates_path
                = nav_link t(:employee), employees_path
                = nav_link t(:result_units), result_units_path
          - if current_organization
            %li.dropdown
              %a.dropdown-toggle{'href' => '#'}
                = t(:accounting)
                %b.caret
              %ul.dropdown-menu
                = nav_link t(:accounting_periods), accounting_periods_path
                = nav_link t(:vat_periods), vat_periods_path
                = nav_link t(:wage_periods), wage_periods_path
                = nav_link t(:opening_balances), opening_balances_path
                = nav_link t(:verificates), verificates_path
                = nav_link t(:closing_balances), closing_balances_path
                = nav_link t(:tax_returns), tax_returns_path

            %li.dropdown
              %a.dropdown-toggle{'href' => '#'}
                = t(:imports)
                %b.caret
              %ul.dropdown-menu
                = nav_link t(:accounting_plan), accounting_plans_path
                = nav_link t(:sie_file), import_sie_files_order_import_sie_path
                = nav_link t(:bank_file), import_bank_files_path
            %li.dropdown
              %a.dropdown-toggle{'href' => '#'}
                = t(:exports)
                %b.caret
              %ul.dropdown-menu
                = nav_link t(:bank_file), import_bank_files_path
            %li.dropdown
              %a.dropdown-toggle{'href' => '#'}
                = t(:reports)
                %b.caret
              %ul.dropdown-menu
                = nav_link t(:verificates), reports_order_verificates_report_path
                = nav_link t(:ledger), ledgers_path
                = nav_link t(:result_report), reports_order_result_report_path
                = nav_link t(:balance_report), reports_order_balance_report_path

        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{'href' => '#'}
              = current_user.name
              %b.caret
            %ul.dropdown-menu
              - if current_user.superadmin?
                %li=link_to t(:admin), admin_dashboard_path
              %li=link_to t(:profile), profile_path
              %li=link_to t(:sign_out), destroy_user_session_path, method: :delete

      - else
        %ul.nav.navbar-nav
          %li
            =link_to t(:about), about_path
          %li
            =link_to t(:sign_in), new_user_session_path

app/views/shared/_notifications.html.haml
- if flash

  // @todo move this into angular, a more generic .js file,
  //       or come up with a pure css solution that works.
  :javascript
    function flashup() { $('.flash').slideUp(500); }
    setTimeout(flashup, 2000);

  - flash.each do |key, message|
    .flash.alert{:class => "alert-#{key} "}
      .container-fluid
        = message

app/views/shared/_search_account.html.haml
%div{ng_controller: 'search_account_ctrl', ng_init: 'init("'+account+'","'+ description+'")'}
  = simple_form_for(model, wrapper: :horizontal_form, html: {class: 'form-horizontal'}) do |f|
    .form-group
      .labels_width.control-label
        %label= t(:accounting_group)
      .fields_width
        %select{ng_model: 'accounting_group', ng_options: "opt.number as opt.name for opt in options", ng_change: 'select_accounting_group();', class: 'select required form-control'}

    .form-group
      .labels_width.control-label
        %label= t(:account)
      .fields_width
        %select{include_blank: false, ng_model: 'acc', ng_options: "account.number as account.description for account in accounts", ng_change: 'select_account();', class: 'select required form-control'}
    %hr