config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'

  root 'pages#start'
  devise_for :users, controllers: {sessions: 'user_sessions'}
  [:about, :start, :formats, :test].each do |p|
    get "/#{p}", to: "pages##{p}"
  end

  namespace :admin do
    resources :organizations
    resources :users do
      member do
        patch 'update_roles', as: :update_roles
      end
    end
    get 'dashboard', to: 'dashboard#index'
    constraints lambda { |request| request.env['warden'].authenticate? && request.env['warden'].user.superadmin? } do
      mount Resque::Server.new, at: "resque"
    end
  end

  get "organization_selector", to: "dashboard#organization_selector"
  get ':organization_slug', to: 'organizations#show', as: 'organization'
  patch ':organization_slug', to: 'organizations#update'

  scope ':organization_slug' do
    get "dashboard", to: "dashboard#index"

    resources :accounting_periods do
      member do
        post 'import_sie', as: :import_sie_files
      end
    end

    post 'accounting_plan_import', to: 'accounting_plans#import', as: 'accounting_plan_import'
    resources :accounting_plans do
      resources :accounting_groups
      resources :accounting_classes
      resources :accounts
    end

    resources :closing_balances do
      resources :closing_balance_items
    end

    resources :contact_relations
    resources :contacts
    resources :conversions do
      delete 'clear'
    end
    resources :employees

    resources :import_bank_files do
      resources :import_bank_file_rows
    end

    get  'import_sie_files/order_import_sie'
    post 'import_sie_files/import_sie'

    resources :ink_codes
    resources :ledgers do
      resources :ledger_accounts
    end
    resources :ledger_transactions

    resources :opening_balances do
      post 'create_from_ub'
      resources :opening_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end

    get 'reports/order_verificates_report'
    get 'reports/order_ledger_report'
    get 'reports/order_result_report'
    get 'reports/order_balance_report'
    post 'reports/verificates'
    post 'reports/ledger'
    post 'reports/result_report'
    post 'reports/balance_report'

    resources :result_units
    resources :tax_codes

    resources :tax_returns do
      resources :tax_return_reports
      member do
        post 'create_tax_return_report', as: :create_tax_return_report
      end
    end

    resources :templates do
      resources :template_items
    end

    resources :users do
      member do
        patch :update_roles, as: :update_roles
      end
    end

    resources :vat_periods do
      resources :vat_reports
      member do
        post 'create_verificate', as: :create_verificate
        post 'create_vat_report', as: :create_vat_report
      end
    end

    resources :verificates do
      resources :verificate_items
      member do
        post 'state_change', as: :state_change
        post 'add_verificate_items', as: :add_verificate_items
      end
    end

    resources :wage_periods do
      resources :wages
      resources :wage_reports
      member do
        post 'create_wage', as: :create_wage
        post 'create_wage_verificate', as: :create_wage_verificate
        post 'create_wage_report', as: :create_wage_report
        post 'create_report_verificate', as: :create_report_verificate
      end
    end

  end

end

app/models/accounting_group.rb
class AccountingGroup < ActiveRecord::Base
  # t.string   :number
  # t.string   :name
  # t.integer  :organization_id
  # t.integer  :accounting_plan_id
  # t.timestamps

  attr_accessible :number, :name

  belongs_to :organization
  belongs_to :accounting_plan
  has_many   :accounts

  validates :number, presence: true, uniqueness: {scope: [:organization_id, :accounting_plan]}
  validates :name, presence: true

  def can_delete?
    return false if accounts.size > 0
    true
  end
end

app/controllers/accounting_groups_controller.rb
class AccountingGroupsController < ApplicationController
  respond_to :html, :json
  load_and_authorize_resource :accounting_plan, through: :current_organization
  load_and_authorize_resource :accounting_group, through: :current_organization

  before_filter :new_breadcrumbs, only: [:new, :create]
  before_filter :show_breadcrumbs, only: [:edit, :show, :update]

  # GET
  def index
    @breadcrumbs = [['Accounting groups']]
  end

  # GET
  def new
  end

  # GET
  def show
  end

  # GET
  def edit
  end

  # POST
  def create
    @accounting_plan = current_organization.accounting_plans.find(params[:accounting_plan_id])
    @accounting_group = @accounting_plan.accounting_groups.build accounting_group_params
    @accounting_group.organization = current_organization
    respond_to do |format|
      if @accounting_group.save
        format.html { redirect_to accounting_plan_path(@accounting_plan), notice: "#{t(:accounting_group)} #{t(:was_successfully_created)}" }
      else
        flash.now[:danger] = "#{t(:failed_to_create)} #{t(:accounting_group)}"
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT
  def update
    respond_to do |format|
      if @accounting_group.update(accounting_group_params)
        format.html { redirect_to accounting_plan_path(@accounting_plan), notice: "#{t(:accounting_group)} #{t(:was_successfully_updated)}" }
      else
        flash.now[:danger] = "#{t(:failed_to_update)} #{t(:accounting_group)}"
        format.html { render action: 'show' }
      end
    end
  end

  # DELETE
  def destroy
    @accounting_group.destroy
    respond_to do |format|
      format.html { redirect_to accounting_plan_path(@accounting_plan), notice:  "#{t(:accounting_group)} #{t(:was_successfully_deleted)}" }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def accounting_group_params
    params.require(:accounting_group).permit(AccountingGroup.accessible_attributes.to_a)
  end

  def new_breadcrumbs
    @breadcrumbs = [[t(:accounting_plans), accounting_plans_path], [@accounting_plan.name, accounting_plan_path(@accounting_plan)], ["#{t(:new)} #{t(:accounting_group)}"]]
  end

  def show_breadcrumbs
    @breadcrumbs = [[t(:accounting_plans), accounting_plans_path], [@accounting_plan.name, accounting_plan_path(@accounting_plan)], [@accounting_group.name]]
  end
end

app/views/accounting_groups/_form.html.haml
= simple_form_for([@accounting_plan, @accounting_group], wrapper: :horizontal_form, html: {class: 'form-horizontal'}) do |f|
  = f.error_notification
  = f.input :number, disabled: !@accounting_group.new_record?
  = f.input :name

  .form-button-group
    .actions
      = f.submit class: 'btn btn-primary'

app/views/accounting_groups/_list.html.haml
- @accounting_groups = @accounting_plan.accounting_groups.order('number').page(params[:page_group])
.btn-group
  = link_to "#{t(:create)} #{t(:accounting_group)}", new_accounting_plan_accounting_group_path(accounting_plan), class: 'btn btn-success'

.table-responsive{:ng_controller=>'ModalCtrl'}
  %table{:class => 'table table-striped'}
    %thead
      %tr
        %th= t(:number)
        %th= t(:name)
        %th
        %th
    %tbody{}
      - @accounting_groups.each do |accounting_group|
        %tr
          %td= accounting_group.number
          %td= accounting_group.name
          %td.numeric= link_to settings_icon, edit_accounting_plan_accounting_group_path(@accounting_plan, accounting_group)
          %td.numeric= delete_modal_for accounting_group, accounting_plan_accounting_group_path(@accounting_plan, accounting_group)

  = paginate @accounting_groups, param_name: "page_group", theme: 'twitter-bootstrap-3'
  = render partial: 'shared/modal_delete', locals: {idx: 'deleteContent'}

app/views/accounting_groups/index.html.haml
.btn-group
  = link_to "#{t(:create)} #{t(:accounting_plan)}", new_accounting_plan_path, class: 'btn btn-success'

.table-responsive{:ng_controller=>'ModalCtrl'}
  %table{:class => 'table table-striped'}
    %thead
      %tr
        %th= t(:name)
        %th= t(:description)
        %th
        %th
    %tbody{}
      - @accounting_plans.each do |accounting_plan|
        %tr
          %td= accounting_plan.name
          %td= accounting_plan.description
          %td.numeric= link_to settings_icon, accounting_plan_path(accounting_plan)
          %td.numeric= delete_modal_for accounting_plan

  = paginate @accounting_plans, :theme => 'twitter-bootstrap-3'
  = render partial: 'shared/modal_delete', locals: {idx: 'deleteContent'}