config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'

  root 'pages#start'
  devise_for :users, controllers: {sessions: 'user_sessions'}
  [:about, :start, :formats, :test].each do |p|
    get "/#{p}", to: "pages##{p}"
  end

  namespace :admin do
    resources :organizations
    resources :users do
      member do
        patch 'update_roles', as: :update_roles
      end
    end
    get 'dashboard', to: 'dashboard#index'
    constraints lambda { |request| request.env['warden'].authenticate? && request.env['warden'].user.superadmin? } do
      mount Resque::Server.new, at: "resque"
    end
  end

  get "organization_selector", to: "dashboard#organization_selector"
  get ':organization_slug', to: 'organizations#show', as: 'organization'
  patch ':organization_slug', to: 'organizations#update'

  scope ':organization_slug' do
    get "dashboard", to: "dashboard#index"

    resources :accounting_periods do
      member do
        post 'import_sie', as: :import_sie_files
      end
    end

    post 'accounting_plan_import', to: 'accounting_plans#import', as: 'accounting_plan_import'
    resources :accounting_plans do
      resources :accounting_groups
      resources :accounting_classes
      resources :accounts
    end

    resources :closing_balances do
      resources :closing_balance_items
    end

    resources :contact_relations
    resources :contacts
    resources :conversions do
      delete 'clear'
    end
    resources :employees

    resources :import_bank_files do
      resources :import_bank_file_rows
    end

    get  'import_sie_files/order_import_sie'
    post 'import_sie_files/import_sie'

    resources :ink_codes
    resources :ledgers do
      resources :ledger_accounts
    end
    resources :ledger_transactions

    resources :opening_balances do
      post 'create_from_ub'
      resources :opening_balance_items
      member do
        post 'state_change', as: :state_change
      end
    end

    get 'reports/order_verificates_report'
    get 'reports/order_ledger_report'
    get 'reports/order_result_report'
    get 'reports/order_balance_report'
    post 'reports/verificates'
    post 'reports/ledger'
    post 'reports/result_report'
    post 'reports/balance_report'

    resources :result_units
    resources :tax_codes

    resources :tax_returns do
      resources :tax_return_reports
      member do
        post 'create_tax_return_report', as: :create_tax_return_report
      end
    end

    resources :templates do
      resources :template_items
    end

    resources :users do
      member do
        patch :update_roles, as: :update_roles
      end
    end

    resources :vat_periods do
      resources :vat_reports
      member do
        post 'create_verificate', as: :create_verificate
        post 'create_vat_report', as: :create_vat_report
      end
    end

    resources :verificates do
      resources :verificate_items
      member do
        post 'state_change', as: :state_change
        post 'add_verificate_items', as: :add_verificate_items
      end
    end

    resources :wage_periods do
      resources :wages
      resources :wage_reports
      member do
        post 'create_wage', as: :create_wage
        post 'create_wage_verificate', as: :create_wage_verificate
        post 'create_wage_report', as: :create_wage_report
        post 'create_report_verificate', as: :create_report_verificate
      end
    end

  end

end

app/models/report.rb
class Report
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  def initialize(accounting_period)
    @accounting_period = accounting_period
  end

  attr_accessor :accounting_period

  def persisted?
    false
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  respond_to :html, :json, :pdf
  #load_and_authorize_resource :accounting_period, through: :current_organization
  #load_and_authorize_resource :verificate, through: :accounting_period
  #load_and_authorize_resource through: :current_organization

  before_filter :new_breadcrumbs, only: [:new, :create]
  before_filter :show_breadcrumbs, only: [:edit, :show, :update]

  def order_verificates_report
    @accounting_period = current_organization.accounting_periods.where('active = true').first
    @report = Report.new @accounting_period
    @accounting_periods = current_organization.accounting_periods
  end

  def verificates
    @report = Report.new params[:report][:accounting_period]
    @accounting_period = current_organization.accounting_periods.find(@report.accounting_period)
    @verificates = current_organization.verificates.where("accounting_period_id = ? AND state = 'final'", @accounting_period.id).order(:number)
    @verificates = @verificates.decorate
    respond_to do |format|
      format.pdf do
        render(pdf: 'verificates', template: 'reports/verificates.pdf.haml', layout: 'pdf')
      end
      format.html
    end
  end

  def order_ledger_report
    @accounting_period = current_organization.accounting_periods.where('active = true').first
    @report = Report.new @accounting_period
    @accounting_periods = current_organization.accounting_periods
  end

  def ledger
    @report = Report.new params[:report][:accounting_period]
    @accounting_period = current_organization.accounting_periods.find(@report.accounting_period)
    @verificate_items = VerificateItem
    .joins(:verificate, :account)
    .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificates.state = 'final'", current_organization.id, @accounting_period.id)
    .select('accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
    .group('accounts.number', 'accounts.description')
    .order('accounts.number')

    respond_to do |format|
      format.pdf do
        render(pdf: 'ledger', template: 'reports/ledger.pdf.haml', layout: 'pdf')
      end
      format.html
    end
  end

  def order_result_report
    @accounting_period = current_organization.accounting_periods.where('active = true').first
    @report = Report.new @accounting_period
    @accounting_periods = current_organization.accounting_periods
  end

  def result_report
    @report = Report.new params[:report][:accounting_period]
    @accounting_period = current_organization.accounting_periods.find(@report.accounting_period)
    @verificate_items = VerificateItem
    .joins(:verificate, :account => :accounting_class)
    .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificates.state = 'final' AND accounting_classes.number > '2999' ", current_organization.id, @accounting_period.id)
    .select('accounting_classes.number AS cls', 'accounting_classes.name AS cls_dsc', 'accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
    .group('accounting_classes.number', 'accounting_classes.name', 'accounts.number', 'accounts.description')
    .order('accounts.number')

    respond_to do |format|
      format.pdf do
        render(pdf: 'ledger', template: 'reports/result.pdf.haml', layout: 'pdf')
      end
      format.html
    end
  end

  def order_balance_report
    @accounting_period = current_organization.accounting_periods.where('active = true').first
    @report = Report.new @accounting_period
    @accounting_periods = current_organization.accounting_periods
  end

  def balance_report
    @report = Report.new params[:report][:accounting_period]
    @accounting_period = current_organization.accounting_periods.find(@report.accounting_period)



    @opening_balance_items =
    @verificate_items = Account
    .joins("INNER JOIN accounting_classes ON accounting_classes.id = accounts.accounting_class_id")
    .select("accounts.number as acc,
accounts.description as desc,
accounting_classes.number as cls,
accounting_classes.name as cls_desc,
(select sum(debit-credit) as ib from opening_balance_items where opening_balance_items.accounting_period_id = #{@accounting_period.id} and opening_balance_items.account_id = accounts.id),
(select sum(debit-credit) as ver from verificate_items where verificate_items.accounting_period_id = #{@accounting_period.id} AND verificate_items.account_id = accounts.id)
")
    .where("accounts.number < '2999'")
    .order('accounts.number')

    @verificate_itemsx = VerificateItem
    .joins(:verificate, :account => :accounting_class)
    .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificates.state = 'final' AND accounting_classes.number < '2999' ", current_organization.id, @accounting_period.id)
    .select('accounting_classes.number AS cls', 'accounting_classes.name AS cls_dsc', 'accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
    .group('accounting_classes.number', 'accounting_classes.name', 'accounts.number', 'accounts.description')
    .order('accounts.number')

    respond_to do |format|
      format.pdf do
        render(pdf: 'ledger', template: 'reports/balance.pdf.haml', layout: 'pdf')
      end
      format.html
    end
  end

  def vat_report
    @report = Report.new(params[:from_short_date], params[:to_short_date])
    @accounting_period = AccountingPeriod.find(params[:report][:accounting_period].to_i)
    @sale_items = VerificateItem
    .joins(:verificate, :account => :accounting_group)
    .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificates.state = 'final' AND accounting_groups.number > '30' AND accounting_groups.number < '35' AND verificates.posting_date > ? AND verificates.posting_date < ? ", current_organization.id, @accounting_period.id, params[:from_short_date], params[:to_short_date])
    .select('accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
    .group('accounts.number', 'accounts.description')
    .order('accounts.number')

    @verificate_items = VerificateItem
    .joins(:verificate, :account => [:accounting_class, :accounting_group])
    .where("verificate_items.organization_id = ? AND verificate_items.accounting_period_id = ? AND verificates.state = 'final' AND accounting_groups.number = '26' ", current_organization.id, @accounting_period.id)
    .select('accounting_classes.number AS cls', 'accounting_classes.name AS cls_dsc', 'accounts.number AS num','accounts.description AS desc', "SUM(debit) AS deb", "SUM(credit) AS cre")
    .group('accounting_classes.number', 'accounting_classes.name', 'accounts.number', 'accounts.description')
    .order('accounts.number')

    respond_to do |format|
      format.pdf do
        render(pdf: 'vat_report', template: 'reports/vat_report.pdf.haml', layout: 'pdf')
      end
      format.html
    end
  end

  # GET
  def index
    @breadcrumbs = [['Verificates']]
    @accounting_periods = current_organization.accounting_periods.where('active = ?', true)
    if !params[:accounting_period_id] && @accounting_periods.count > 0
      params[:accounting_period_id] = @accounting_periods.first.id
    end
    @verificates = current_organization.verificates.where('accounting_period_id=?', params[:accounting_period_id]).order(:number)
    @verificates = @verificates.page(params[:page]).decorate
  end

  # GET
  def new
    @accounting_periods = current_organization.accounting_periods.where('active = ?', true)
    gon.push accounting_periods: ActiveModel::ArraySerializer.new(@accounting_periods, each_serializer: AccountingPeriodSerializer)
    @templates = current_organization.templates
  end

  # GET
  def show
    @accounting_periods = current_organization.accounting_periods.where('active = ?', true)
    gon.push accounting_periods: ActiveModel::ArraySerializer.new(@accounting_periods, each_serializer: AccountingPeriodSerializer)
  end

  # GET
  def edit
  end

  # POST
  def create
    Rails.logger.info "#{params.inspect}"
    if !params[:template].blank?
      template = current_organization.templates.find(params[:template])
      params[:verificate][:description] = template.description + params[:verificate][:description]
    end
    #@accounting_period = current_organization.accounting_periods.find(params[:accounting_period_id])
    #@verificate = @accounting_period.verificates.build verificate_params
    @verificate = Verificate.new(verificate_params)
    @verificate.organization = current_organization
    respond_to do |format|
      if @verificate.save
        format.html { redirect_to verificate_path(@verificate), notice: "#{t(:verificate)} #{t(:was_successfully_created)}" }
      else
        flash.now[:danger] = "#{t(:failed_to_create)} #{t(:verificate)}"
        @accounting_periods = current_organization.accounting_periods.where('active = ?', true)
        gon.push accounting_periods: ActiveModel::ArraySerializer.new(@accounting_periods, each_serializer: AccountingPeriodSerializer)
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT
  def update
    respond_to do |format|
      if @verificate.update(verificate_params)
        format.html { redirect_to verificates_path, notice: "#{t(:verificate)} #{t(:was_successfully_updated)}" }
      else
        flash.now[:danger] = "#{t(:failed_to_update)} #{t(:verificate)}"
        @accounting_periods = current_organization.accounting_periods.where('active = ?', true)
        gon.push accounting_periods: ActiveModel::ArraySerializer.new(@accounting_periods, each_serializer: AccountingPeriodSerializer)
        format.html { render action: 'show' }
      end
    end
  end

  # DELETE
  def destroy
    @verificate.destroy
    respond_to do |format|

app/views/reports/balance.pdf.haml
- save_class = ''
%table.wrapper
  %tr
    %td{colspan: '2'}
      .pull-left
        %h1= t(:balance)
      .pull-right
        %h1= @accounting_period.name
  %tr
    %td.sale_item_wrapper{colspan: '2'}
      %table.table.table-striped
        - @verificate_items.each do |item|
          - if save_class != item.cls
            - save_class = item.cls
            %tr.filler
              %td{colspan:'5'} &nbsp;
            %tr
              %th{colspan: '2'}=item.cls_desc
              %th.numeric= t(:ib)
              %th.numeric= t(:change)
              %th.numeric= t(:ub)
          - if !item.ver.nil? || !item.ib.nil?
            - ver = item.ver.nil? ? 0 : item.ver
            - ib = item.ib.nil? ? 0 : item.ib
            - sum = ib + ver
            %tr
              %td.short=item.acc
              %td= item.desc
              %td.numeric= item.ib
              %td.numeric= item.ver
              %td.numeric= sum

app/views/reports/ledger.pdf.haml
%table.wrapper
  %tr
    %td{colspan: '2'}
      .pull-left
        %h1= t(:ledger)
      .pull-right
        %h1= @accounting_period.name
  %tr
    %td.sale_item_wrapper{colspan: '2'}
      %table.table.table-striped
        %tr
          %th= t(:account)
          %th= t(:description)
          %th= t(:debit)
          %th= t(:credit)

        - @verificate_items.each do |item|
          %tr
            %td=item.num
            %td=item.desc
            %td=item.deb
            %td=item.cre

app/views/reports/order_balance_report.html.haml
%h4= t(:balance_report)
= simple_form_for(@report, wrapper: :horizontal_form, html: {class: 'form-horizontal', target: "_blank" }, url: reports_balance_report_path(report_id: 0, format: 'pdf')) do |f|
  = f.error_notification
  = f.input :accounting_period, as: :select, collection: @accounting_periods, include_blank: false, selected: @accounting_period.id

  .form-button-group
    .actions
      = f.submit class: 'btn btn-primary'

app/views/reports/order_ledger_report.html.haml
%h4= t(:ledger_report)
= simple_form_for(@report, wrapper: :horizontal_form, html: {class: 'form-horizontal', target: "_blank" }, url: reports_ledger_path(report_id: 0, format: 'pdf')) do |f|
  = f.error_notification
  = f.input :accounting_period, as: :select, collection: @accounting_periods, include_blank: false, selected: @accounting_period.id

  .form-button-group
    .actions
      = f.submit class: 'btn btn-primary'

app/views/reports/order_result_report.html.haml
%h4= t(:result_report)
= simple_form_for(@report, wrapper: :horizontal_form, html: {class: 'form-horizontal', target: "_blank" }, url: reports_result_report_path(report_id: 0, format: 'pdf')) do |f|
  = f.error_notification
  = f.input :accounting_period, as: :select, collection: @accounting_periods, include_blank: false, selected: @accounting_period.id

  .form-button-group
    .actions
      = f.submit class: 'btn btn-primary'

app/views/reports/order_verificates_report.html.haml
%h4= t(:list_of_verificates)
= simple_form_for(@report, wrapper: :horizontal_form, html: {class: 'form-horizontal', target: "_blank" }, url: reports_verificates_path(report_id: 0, format: 'pdf')) do |f|
  = f.error_notification
  = f.input :accounting_period, as: :select, collection: @accounting_periods, include_blank: false, selected: @accounting_period.id

  .form-button-group
    .actions
      = f.submit class: 'btn btn-primary'

app/views/reports/result.pdf.haml
- save_class = ''
%table.wrapper
  %tr
    %td{colspan: '2'}
      .pull-left
        %h1= t(:result)
      .pull-right
        %h1= @accounting_period.name
  %tr
    %td.sale_item_wrapper{colspan: '2'}
      %table.table.table-striped
        - @verificate_items.each do |item|
          - if save_class != item.cls
            - save_class = item.cls
            %tr.filler
              %td{colspan:'4'} &nbsp;
            %tr
              %th.main=item.cls
              %th= item.cls_dsc
              %th
          %tr
            - sum = -item.deb + item.cre
            %td.main=item.num
            %td=item.desc
            %td.numeric=sum

app/views/reports/verificates.pdf.haml
%table.wrapper
  %tr
    %td{colspan: '2'}
      .pull-left
        %h1= t(:verificates)
      .pull-right
        %h1= @verificates.first.accounting_period.name
  %tr
    %td.sale_item_wrapper{colspan: '2'}
      %table.table.table-striped
        - @verificates.each do |ver|
          %tr
            %th.main= t(:number) + ": #{ver.number}"
            %th=ver.description
            %th{colspan: '2'}=ver.posting_date
            %th
          - ver.verificate_items.each do |item|
            - item = item.decorate
            %tr
              %td.main= item.account_number
              %td= item.description
              %td.numeric= item.debit
              %td.numeric= item.credit
          %tr.filler
            %td{colspan:'5'} &nbsp;